version: '3'
services:
  db:
    image: mysql:latest
    ports:
     - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD:
  spring-music:
    build: .
    links:
     - db
    depends_on:
     - db
    ports:
     - 8090:8080
    tty: true
    stdin_open: true
    restart: always